const localStorageKey = 'area_data'

export default () => {
  return JSON.parse(localStorage.getItem(localStorageKey))
}

if (!localStorage.getItem(localStorageKey)) {
  localStorage.setItem(localStorageKey, JSON.stringify([{ 'label': 'Northern Region', 'value': 'AUS0NT', 'children': [{ 'label': 'Darwin', 'value': 'AUS0NTDRW' }, { 'label': 'North Palmerston', 'value': 'AUS0NTPAL' }] }, { 'label': 'South Australia', 'value': 'AUS0SA', 'children': [{ 'label': 'Adelaide', 'value': 'AUS0SAADL' }, { 'label': 'Gambian Mountain', 'value': 'AUS0SAMGB ' }, { 'label': 'Murray Bridge', 'value': 'AUS0SAMYB' }, { 'label': 'Lincoln Port', 'value': 'AUS0SAPLO' }, { 'label': ' Piri Port', 'value': 'AUS0SAPPI' }, { 'label': 'Augusta Port', 'value': 'AUS0SAPUG' }, { 'label': 'Victor Port', 'value': 'AUS0SAVHA' }, { 'label': 'Waiala', 'value': 'AUS0SAWAY' }] }, { 'label': 'Western Australia', 'value': 'AUS0WA', 'children': [{ 'label': 'Albani', 'value': 'AUS0WAALH' }, { 'label': 'Banbury', 'value': 'AUS0WABUY' }, { 'label': 'Port of Fremantle', 'value': 'AUS0WAFRE' }, { 'label': 'Geraldton', 'value': 'AUS0WAGET' }, { 'label': 'Kalguly', 'value': 'AUS 0WAKGI' }, { 'label': 'Manzhera', 'value': 'AUS0WAMDU' }, { 'label': 'Perth', 'value': 'AUS0WAPER' }] }, { 'label': 'Canberra', 'value': 'AUSACT', 'children': [{ 'label': 'Canberra', 'value': 'AUSACTCBR' }] }, { 'label': 'New South Wales', 'value': 'AUSNSW', 'children': [{ 'label': 'Sydney', 'value': 'AUSNSWHBS' }, { 'label': 'Newcastle', 'value': 'AUSNSWNTL' }, { 'label ': 'Wollongong', 'value': 'AUSNSWWOL' }] }, { 'label': 'Queensland', 'value': 'AUSQLD', 'children': [{ 'label': 'Brisbane', 'value': 'AUSQLDBNE' }, { 'label': 'Keynes', 'value': 'AUSQLDCNS' }, { 'label': 'Sun Coast', 'value': 'AUSQLDCUD' }, { 'label': 'Gold Coast', 'value': 'AUSQLDOOL' }, { 'label': 'Tonsville', 'value': 'AUSQLDTSV' }, { 'label': 'Toowoomba', 'value': 'AUSQLDTWB' }] }, { 'label': 'Tasmania', 'value': 'AUSTAS', 'children': [{ 'label': 'Bernie Port', 'value': 'AUSTASBWT ' }, { 'label': 'Devonport', 'value': 'AUSTASDPO' }, { 'label': 'Hobart', 'value': 'AUSTASHBA' }, { 'label': 'Lanceston', 'value': 'AUSTASLST' }] }, { 'label': 'Victoria', 'value': 'AUSVIC', 'children': [{ 'label': 'Geelong', 'value': 'AUSVICGEX' }, { 'label': 'Melbourne', 'value': 'AUSVICMEL' }] }]))
}

